Remove registration, include metadata with reports
judoscale/judoscale-ruby pull request #50
Opened 2022-03-05 17:35 UTC by carlosantoniodasilva

Simplify the reporter logic by always including contextual metadata with
each report, and removing the initial registration step which included
such metadata.

The metadata is important for support/troubleshooting/debugging
purposes, and keeping it on every report to the API keeps these reports
more self-contained in general, and simplifies the code considerably.

2022-03-06 13:55 UTC, adamlogic requested changes
Look at all that deleted code! 🥳

2022-03-06 13:55 UTC, adamlogic commented on judoscale-ruby/lib/judoscale/reporter.rb
> +        log_exceptions { report!(config, []) }
We won't have any request metrics yet, but ideally this initial report could include job metrics. WDYT of removing this, then changing the order of the loop so that the reporting happens _before the `sleep`_?

I think that would accomplish having an initial report as soon as the reporter starts, which includes job metrics. Then subsequent reporting would be every ~10 seconds.

2022-03-08 00:53 UTC, carlosantoniodasilva commented on judoscale-ruby/lib/judoscale/reporter.rb
> +        log_exceptions { report!(config, []) }
I didn't think we'd need/want the job metrics on this first report, but I could see how this makes sense. I guess there's no problem in hitting them as soon as the reporter starts (e.g. on app boot once we have that), I'll make the change.

2022-03-08 13:23 UTC, adamlogic approved these changes
❤️

2022-03-09 02:37 UTC, merged