Minitest Example
judoscale/judoscale-ruby pull request #8
Opened 2021-12-21 12:55 UTC by carlosantoniodasilva

Implement the logger tests using minitest

This is a sample of how tests could look like with Minitest, if we want
to go down that route of converting them.

It's a bit of a manual process, but this has the setup necessary to make
it work. Minitest also has a more spec-like syntax that's similar to
RSpec, if we wanted to use it, but this just goes with the most bare and
common Minitest usage.

I also ran into a bit of an issue with the ENV swapping usage/helper,
because of the callbacks nature of things it doesn't work the same way
here, so I switch that to swap the config instead. I guess that makes
sense, that the logger doesn't need to be concerned about the ENV var
but just the config, and we could test the ENV var elsewhere (e.g. in
the config tests.)

2021-12-21 12:58 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +      use_config debug: true do
I had to change this from `use_env` to `use_config` due to how the ENV sets up the Config.instance upfront, and how callbacks wrap specs in RSpec vs Minitest here, but other than that, this should be essentially testing the same thing as the existing logger_spec.

2021-12-21 12:58 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +    def test_info_delegates_to_the_original_logger_prepending_judoscale
There's an alternative of using [ActiveSupport::TestCase](https://api.rubyonrails.org/classes/ActiveSupport/TestCase.html), which gives us some extra assertions and the ability to write tests in a block way, e.g.:

```ruby
test "info delegates to the original logger prepending Judoscale" do
  ...
end
```

2021-12-21 13:19 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +    def test_info_delegates_to_the_original_logger_prepending_judoscale
There's an example of AS::TestCase for comparison [at the bottom of this blog post](http://blog.plataformatec.com.br/2015/05/nobody-told-me-minitest-was-this-fun/).

2021-12-21 18:08 UTC, adamlogic reviewed
> Minitest also has a more spec-like syntax that's similar to
RSpec, if we wanted to use it, but this just goes with the most bare and
common Minitest usage.

I forgot about this as well. I do think I'd prefer to use minitest/spec, just because I always forget the order of arguments to `assert_equal`. 🤷‍♂️

2021-12-21 18:08 UTC, adamlogic commented on test/logger_test.rb
> +    def test_info_delegates_to_the_original_logger_prepending_judoscale
Yes, I totally forgot that bare Minitest requires `snake_case` test names. I'm 100% in favor of using ActiveSupport::TestCase.

2021-12-22 13:11 UTC, carlosantoniodasilva commented
Here is a sample of the changes to use AS::TestCase: https://github.com/judoscale/judoscale-ruby/compare/main...judoscale:ca-minitest-as-testcase, it's a bit of an improvement over bare Minitest, in terms of readability.

And here is a sample of Minitest::Spec: https://github.com/judoscale/judoscale-ruby/compare/main...judoscale:ca-minitest-spec  (this has [one commit that does not use `let`](https://github.com/judoscale/judoscale-ruby/commit/93f4419ee1a66c69d9c7932ee289d40ca4752092), and [one that introduces it](https://github.com/judoscale/judoscale-ruby/commit/a62ba89c985a7a1c19b3e98e7358df52982ea399)) 

Minitest::Spec feels very much like RSpec, which means it's much more comfortable for anyone used to it. You need a bit of adjustment with the must/won't matchers but that's about it (and no problems with order of arguments like `assert_equal`.) And you can mix and match with assertions and even inherit from Minitest::Spec if you don't want to write `describe` at the top level / globally (something Rspec has been slowly moving away from).

It's also a much easier conversion from Rspec to Minitest::Spec, for sure.

2021-12-22 14:43 UTC, adamlogic commented
Nice! Thanks for providing these examples.

I really like the `AS::TestCase` sugar, and I also like the `Minitest::Spec` syntax with `let`.

> and even inherit from Minitest::Spec if you don't want to write describe at the top level / globally (something Rspec has been slowly moving away from)

I have no opinion here, so whatever you decide to roll with is great. 👍

2021-12-28 13:02 UTC, carlosantoniodasilva commented
I think mixing `AS::TestCase` with `Minitest:Spec` for expectations is gonna be a bit confusing (to avoid things like `assert_equal` and arguments order), so I think we could go all in with `Minitest::Spec`. It should be an easier conversion.

2021-12-28 14:50 UTC, adamlogic commented
Oh, right. The main driver for me wanting `AS::TestCase` was to avoid having to define tests in snake_case, but `Minitest::Spec` also handles this.

All in on `Minitest::Spec` sounds good!

2021-12-29 13:26 UTC, carlosantoniodasilva reviewed
@adamlogic this is the least effort conversion to Minitest::Spec... for the most part it's similar, some stubbing/mocking is sometimes a bit more complicated with Minitest but it's always doable without adding other dependencies.

It looks like the VCR error I was hitting before has become more apparent now, it seems to be fail somewhat consistently on this branch. I will try to look into it, but wanted to send you this to have a better idea of what the conversion would look like, so we can decide if that's the path forward, or if sticking to rspec would be a possible better option.

_Note_: I tried to minimize the changes to the specs, mostly touching what was needed to make them work with minitest and stubbing.

2021-12-29 13:26 UTC, carlosantoniodasilva commented on .vscode/tasks.json
> +      "args": ["exec", "rake test TEST=${relativeFile}"],
I have not figured out a way to run a specific line number directly from rake like this, I know you can do it via a test name, but a line number might need some magic.

2021-12-29 13:26 UTC, carlosantoniodasilva commented on test/support/env_helpers.rb
> +    Judoscale::Config.instance
Minitest doesn't have an "around" concept, just before/after (setup/teardown), so I ended up forcing a config reset here to make sure it would inherit the updated ENVs.

I think later we could look into using config swapping instead of ENV swapping in most places, and leave the ENV swapping to test the config itself, to simplify this.

2021-12-29 13:26 UTC, carlosantoniodasilva commented on test/middleware_test.rb
> +          before {
Can only have a single before/after (setup/teardown) block

2021-12-29 13:26 UTC, carlosantoniodasilva commented on test/autoscale_api_test.rb
> +require "minitest-vcr"
I ended up adding an extra dependency to facilitate VCR integration. Not sure how strong you feel about VCR, but one thing we could possibly do is to use bare Webmock to handle these tests, I sometimes feel like VCR is a lot of trouble.

2021-12-29 13:26 UTC, carlosantoniodasilva commented on test/worker_adapters/resque_test.rb
> +          ::Resque.stub(:size, ->(queue_name) { sizes.fetch(queue_name) }) {
This is where stubbing might feel a bit more complicated initially for anyone used to RSpec, since it's usually so easy to stub anything there... but since it's just Ruby it becomes easier over time, I think.

And I kinda like the approach of stubbing with a block, meaning the stub is only valid for the duration of that block.

2021-12-29 16:14 UTC, adamlogic reviewed
I like where this is headed!

2021-12-29 16:14 UTC, adamlogic commented on .vscode/tasks.json
> +      "args": ["exec", "rake test TEST=${relativeFile}"],
The tests are so fast that I don't think there's a need to run a single line. Let's remove that task.

2021-12-29 16:14 UTC, adamlogic commented on test/autoscale_api_test.rb
> +require "minitest-vcr"
I'm 100% on board to remove VCR.

I think it's often helpful to avoid really verbose mocking via Webmock, but that's definitely not the case here. There's only a few cassettes in use, and the responses are tiny.

2021-12-29 16:14 UTC, adamlogic commented on test/middleware_test.rb
> +          before {
👍 No problem.

Is there a difference between a `before` block and `def setup`?

I don't think I have a preference between the two, but if they do the same thing, I just want to make sure we're consistent.

2021-12-29 16:14 UTC, adamlogic commented on test/worker_adapters/resque_test.rb
> +          ::Resque.stub(:size, ->(queue_name) { sizes.fetch(queue_name) }) {
I also like the explicitness of stubbing with a block. My only gripe is that we have to nest two blocks here. I kind of want to override `stub` (or add `stubs` as a new method) to support passing a Hash that specifies multiple stubs in one block.

We don't need to do that here, but curious what you think.

2021-12-29 19:22 UTC, carlosantoniodasilva commented on test/middleware_test.rb
> +          before {
`before` is just syntax sugar for `setup`, something like this: `def setup(&block); super; block.call; end`, however because of that we can't call `super` from within `before` since it's probably running the passed block via instance eval (which is why I had to use `def setup` for the `use_env` calls), and you can't define multiple `before` otherwise that'd essentially override the previously defined one.

I want to get rid of those `def setup` though.

2021-12-29 19:24 UTC, carlosantoniodasilva commented on test/worker_adapters/resque_test.rb
> +          ::Resque.stub(:size, ->(queue_name) { sizes.fetch(queue_name) }) {
Cool, yeah it gets overly verbose with multiple blocks, I agree some helper to simplify that when stubbing on the same object would be helpful. When we're dealing with different objects though, I am not sure there's much way around it, but it's not the case here.

2021-12-29 19:36 UTC, carlosantoniodasilva commented
Note: There's a random failure that is reproducible, I think it's related to the order of tests possibly leaving something in the store affecting later tests.

```
% be rake TESTOPTS="--seed=46035"


Finished in 0.286438s, 146.6286 runs/s, 352.6068 assertions/s.

  1) Failure:
Judoscale::WorkerAdapters::Que::#collect!#test_0001_collects latency for each queue [/Users/carlos/src/judoscale/judoscale-ruby/test/worker_adapters/que_test.rb:38]:
Expected: 2
  Actual: 3

42 runs, 101 assertions, 1 failures, 0 errors, 0 skips
```

2022-01-10 23:04 UTC, carlosantoniodasilva commented
@adamlogic have you had any intermittent test issues before? I've been trying to figure out why most of the time the suite failed in this branch, I could repro it consistently with these two seeds: (they're failing on different tests for the same middleware test)

```
% bundle exec rake TESTOPTS="--seed=47122"
...
Run options: --seed=47122

# Running:

.....F....................................

Finished in 0.383004s, 109.6594 runs/s, 274.1486 assertions/s.

  1) Failure:
Judoscale::Middleware::#call::with JUDOSCALE_URL set::when the request includes HTTP_X_REQUEST_START#test_0002_records the queue time in the environment passed on [/Users/carlos/src/judoscale/judoscale-ruby/test/middleware_test.rb:69]:
Expected |5000 - 5023| (23) to be <= 1.

42 runs, 105 assertions, 1 failures, 0 errors, 0 skips

% bundle exec rake TESTOPTS="--seed=1829"
...
Run options: --seed=1829

# Running:

....F.....................................

Finished in 0.426780s, 98.4114 runs/s, 246.0284 assertions/s.

  1) Failure:
Judoscale::Middleware::#call::with JUDOSCALE_URL set::when the request includes HTTP_X_REQUEST_START#test_0001_collects the request queue time [/Users/carlos/src/judoscale/judoscale-ruby/test/middleware_test.rb:62]:
Expected |5000 - 5100| (100) to be <= 1.

42 runs, 105 assertions, 1 failures, 0 errors, 0 skips
```

I _think_ I have pinpointed the issue to the queue time being calculated _after_ the reporter is started/registered, which is usually super fast in the test but for some reason is more apparent now. I'm assuming the same would happen in production, that the first hit to the app that inits the reporter causes the queue time to be slightly higher since it includes it.

I've tried the following change and it appears to solve the test errors for me:

```
diff --git a/lib/judoscale/middleware.rb b/lib/judoscale/middleware.rb
index 2b41701..a2a69e1 100644
--- a/lib/judoscale/middleware.rb
+++ b/lib/judoscale/middleware.rb
@@ -15,10 +15,12 @@ module Judoscale
       config = Config.instance
       request = Request.new(env, config)

+      queue_time = request.queue_time unless request.ignore?
+
       store = Store.instance
       Reporter.start(config, store)

-      if !request.ignore? && (queue_time = request.queue_time)
+      if queue_time
         # NOTE: Expose queue time to the app
         env["queue_time"] = queue_time
         store.push queue_time
```

2022-01-10 23:05 UTC, carlosantoniodasilva commented
@adamlogic have you had any intermittent test issues before? I've been trying to figure out why most of the time the suite failed in this branch, I could repro it consistently with these two seeds: (they're failing on different tests for the same middleware test)

```
% bundle exec rake TESTOPTS="--seed=47122"
...
Run options: --seed=47122

# Running:

.....F....................................

Finished in 0.383004s, 109.6594 runs/s, 274.1486 assertions/s.

  1) Failure:
Judoscale::Middleware::#call::with JUDOSCALE_URL set::when the request includes HTTP_X_REQUEST_START#test_0002_records the queue time in the environment passed on [/Users/carlos/src/judoscale/judoscale-ruby/test/middleware_test.rb:69]:
Expected |5000 - 5023| (23) to be <= 1.

42 runs, 105 assertions, 1 failures, 0 errors, 0 skips

% bundle exec rake TESTOPTS="--seed=1829"
...
Run options: --seed=1829

# Running:

....F.....................................

Finished in 0.426780s, 98.4114 runs/s, 246.0284 assertions/s.

  1) Failure:
Judoscale::Middleware::#call::with JUDOSCALE_URL set::when the request includes HTTP_X_REQUEST_START#test_0001_collects the request queue time [/Users/carlos/src/judoscale/judoscale-ruby/test/middleware_test.rb:62]:
Expected |5000 - 5100| (100) to be <= 1.

42 runs, 105 assertions, 1 failures, 0 errors, 0 skips
```

I _think_ I have pinpointed the issue to the queue time being calculated _after_ the reporter is started/registered, which is usually super fast in the test but for some reason is more apparent now. I'm assuming the same would happen in production, that the first hit to the app that inits the reporter causes the queue time to be slightly higher since it includes it.

I've tried the following change and it appears to solve the test errors for me:

```diff
diff --git a/lib/judoscale/middleware.rb b/lib/judoscale/middleware.rb
index 2b41701..a2a69e1 100644
--- a/lib/judoscale/middleware.rb
+++ b/lib/judoscale/middleware.rb
@@ -15,10 +15,12 @@ module Judoscale
       config = Config.instance
       request = Request.new(env, config)

+      queue_time = request.queue_time unless request.ignore?
+
       store = Store.instance
       Reporter.start(config, store)

-      if !request.ignore? && (queue_time = request.queue_time)
+      if queue_time
         # NOTE: Expose queue time to the app
         env["queue_time"] = queue_time
         store.push queue_time
```

```
% bundle exec rake TESTOPTS="--seed=1829"
...
Run options: --seed=1829

# Running:

..........................................

Finished in 0.374235s, 112.2289 runs/s, 280.5724 assertions/s.

42 runs, 105 assertions, 0 failures, 0 errors, 0 skips

~/src/judoscale/judoscale-ruby [3.0.3] (ca-minitest *$%=)
% bundle exec rake TESTOPTS="--seed=47122"
...
Run options: --seed=47122

# Running:

..........................................

Finished in 0.358865s, 117.0357 runs/s, 292.5891 assertions/s.

42 runs, 105 assertions, 0 failures, 0 errors, 0 skips
```

2022-01-11 13:09 UTC, adamlogic commented
> have you had any intermittent test issues before?

My work on this gem has been so intermittent that I can't even remember if I've had issues before. Beyond that, CI wasn't running for many months after travisci.org shut down, and I wasn't disciplined about running the specs locally.

> I wanted to run the change by you, since I was mostly trying to update the tests here, but it seems to make sense.

Yes, this is a good change for sure! Since `Reporter.start` spins off a new thread the first time it is called, we might be at the whim of Ruby's thread scheduler for when the main thread proceeds.

Great catch!

2022-01-12 22:53 UTC, carlosantoniodasilva commented
Cool, that makes sense, thanks for the additional context. I pushed that last change 7bf1a8206fa035e6c93b0a9d85194b185db35858 and the branch is now green on Minitest, I think this one should be good for another look.

2022-01-13 17:35 UTC, adamlogic commented
@carlosantoniodasilva I'm was seeing several instances of this failure within resque when I ran `bundle exec rake`:

```
Judoscale::Middleware::#call::without JUDOSCALE_URL set#test_0001_passes the request up the middleware stack:
NameError: uninitialized constant Rails::Railtie
    /Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/resque-2.1.0/lib/resque/railtie.rb:2:in `<module:Resque>'
    /Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/resque-2.1.0/lib/resque/railtie.rb:1:in `<top (required)>'
    /Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/resque-2.1.0/lib/resque.rb:26:in `<top (required)>'
    /Users/adam/src/judoscale-ruby/lib/judoscale/worker_adapters/resque.rb:18:in `enabled?'
```

I noticed that `Gemfile.lock` is in `.gitignore`, so each test runner is going to resolve its own gems. Apparently on my machine I already had Resque 2.1.0 installed, so it used that. The test runners in GitHub are using 2.2.0. This is from GH Actions output:

```
  Using resque 2.2.0
```

I removed my local `Gemfile.lock`, re-installed `resque`, and the tests passed:

```
judoscale-ruby $ rm Gemfile.lock 
judoscale-ruby $ gem install resque
Fetching resque-2.2.0.gem
Successfully installed resque-2.2.0
Parsing documentation for resque-2.2.0
Installing ri documentation for resque-2.2.0
Done installing documentation for resque after 0 seconds
1 gem installed
judoscale-ruby $ be rake
/Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:288: warning: method redefined; discarding old max_attempts
/Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:22: warning: previous definition of max_attempts was here
/Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:292: warning: method redefined; discarding old max_run_time
/Users/adam/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:22: warning: previous definition of max_run_time was here
-- create_table(:delayed_jobs)
   -> 0.0029s
-- create_table("que_jobs")
   -> 0.0002s
Run options: --seed 11310

# Running:

..........................................

Finished in 0.263396s, 159.4557 runs/s, 398.6393 assertions/s.

42 runs, 105 assertions, 0 failures, 0 errors, 0 skips
judoscale-ruby $ 
```

I can see the `Gemfile.lock` [has been ignored](https://github.com/judoscale/judoscale-ruby/blame/ca-minitest/.gitignore#L3) since I originally built this gem via `bundle gem` 6 years ago.

**I think we should commit `Gemfile.lock` to ensure that all test runs use the same gem versions.**

I can't think of a good reason to ignore it. Can you?

---

The other question is the failure itself. [Resque 2.1.0 has an unexpected dependency on `Railtie`](https://github.com/resque/resque/issues/1764), but I would assume anyone who is using Resque 2.1.0 without Rails would have already run into this issue before installing Judoscale.

I think it's safe to ignore here.

2022-01-13 17:52 UTC, carlosantoniodasilva commented
@adamlogic ah, I ran into a somewhat similar issue with standardrb, because the `Gemfile.lock` wasn't committed the GH Action was using the latest, and when they released a new one the lint automatically failed due to a rubocop addition. I fixed those warnings in b8d33312605076c5073341760d772f3a41c5e891 (already in main).

IIRC When the lock files were introduced initially, [they advised not to commit them](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/), but over time I think it just became clear that it was better for development purposes to have everyone developing the libraries using the same dependency versions, and that it would not enforce those same versions on anyone using the libraries in question.

Yes, I think committing the `main Gemfile.lock` would be good, that's how I generally do for other open source projects like Devise. It helps ensure everyone developing has the same set of gems installed, avoiding running into these types of issues. Another thing we can possibly do later is to setup the testing matrix to try different versions of Rails & the supported worker libraries as well, to help ensure coverage and catch possible issues across different versions.

2022-01-13 17:56 UTC, adamlogic requested changes
@carlosantoniodasilva This is looking great! Just a couple small questions before merging.

2022-01-13 17:56 UTC, adamlogic commented on test/logger_test.rb
> +        def setup
I had to revisit our [previous discussion](https://github.com/judoscale/judoscale-ruby/pull/8#discussion_r776464995) to remember why we're using `def setup` here and `before do` up above.

How hard would it be to make `use_env` in the same scope as `before` and `it` so we can call it directly here? I'm thinking it would include the logic to hook into `setup` so we would call `use_env` *instead of* `def setup` or `before`.

If that's a pain, let's maybe just add a comment here explaining that we have to use `def setup` so we can call `super`.

2022-01-13 17:56 UTC, adamlogic commented on test/middleware_test.rb
> +        Reporter.instance.stop!
👍

2022-01-13 17:56 UTC, adamlogic commented on test/middleware_test.rb
> +          Reporter.instance.stub(:register!, -> { raise "NEVER CALLED" }) do
```suggestion
          Reporter.instance.stub(:register!, -> { raise "SHOULD NOT BE CALLED" }) do
```

Just a slight clarification here since I think it might be confusing to see a "never called" exception when a method *was* called.

2022-01-13 17:56 UTC, adamlogic commented on test/reporter_test.rb
> +        assert_request_requested stub
Where is `assert_request_requested` coming from? It looks like [Webmock defines `assert_requested`](https://github.com/bblimke/webmock#setting-expectations-in-testunit-on-the-stub).

2022-01-13 18:00 UTC, carlosantoniodasilva commented on test/reporter_test.rb
> +        assert_request_requested stub
It should be `assert_requested` indeed, but I apparently reached out to the internal/private API directly while looking at their code: https://github.com/bblimke/webmock/blob/33d8810c2828fc17010e15cc3f21ad2c726a966f/lib/webmock/api.rb#L20-L27

I'll update :+1:

2022-01-13 18:02 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +        def setup
Right, I can see how it can be confusing especially when revisiting this in the future, I'll take a look to see if I can wrap this up in something nicer.

2022-01-13 21:11 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +        def setup
@adamlogic I was starting to explore moving `use_env` to the same level of `before`/`it`, but this other idea came to mind and I wanted to run it by you: split the test setup & restoration into two distinct steps (essentially a "before" and "after" step), we can use the `before` blocks to setup the ENV for the necessary tests, and automatically restore / revert back on teardown / "after".

Here's one possible implementation to handle it like that, using the before block and a default "after_teardown"  hook from minitest that only exists in the supporting code: (this is a separate branch that I just pushed to facilitate the diff) https://github.com/judoscale/judoscale-ruby/compare/ca-minitest...judoscale:ca-minitest-use-env 

Let me know what you think.

2022-01-13 22:08 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +        def setup
I forgot to mention that I think we can eventually move away from most `env` swapping usage and use `config` swapping instead: we can change the config we control for the tests that rely on those configs to test different behavior, and possibly only touch the env to test the configs that load from it. I can track that as part of future test improvements, I didn't want to make many more changes to this one.

2022-01-13 22:46 UTC, adamlogic commented on test/logger_test.rb
> +        def setup
@carlosantoniodasilva I'm happy to move forward with that! 👍

2022-01-13 23:05 UTC, carlosantoniodasilva commented on test/logger_test.rb
> +        def setup
Cool, I pushed the changes to this branch now.

2022-01-14 21:13 UTC, merged